version: '3.1'
services:
  mysql:
    container_name: demo-sf4-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4
#    volumes:
#      - ./docker/mysql:/var/lib/mysql
  phpmyadmin:
    container_name: demo-sf4-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - 8082:80

  httpd:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/dockerfile/Dockerfile.httpd-fpm
    container_name: demo-sf4-httpd
    volumes:
      - ./docker/resources/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - .:/var/www/html/current:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - php
    ports:
      - 8083:80
    
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/dockerfile/Dockerfile.php-fpm71
    container_name: demo-sf4-php7
    volumes:
      - ./:/var/www/html/current
      - ./docker/resources/php.ini:/usr/local/etc/php/php.ini:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - mysql
